site:
  title: Test Docs Site
  url: /docs/fast-pulsar-jms
  start_page: test::index.adoc

content:
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/raw/main/releases/download/v0.7/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: assets

asciidoc:
  attributes:
    source-highlighter: highlightjs
  extensions:
  - ./lib/tabs-block.js